spring:
  datasource:
    url: jdbc:sqlserver://shubhamshrma2803.database.windows.net:1433;database=shubhamdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: shubhamshrma2803
    password: Password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191